title = "如创科技"
baseURL = "https://www.rutron.net/"
defaultContentLanguage = 'zh'
languageCode = "zh"
# themesDir = ".."
theme = "github.com/llaoj/hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo.png"
    mobile_height = "40px"
    mobile_width = "40px"
    desktop = "images/logo.png"
    desktop_height = "40px"
    desktop_width = "40px "
    alt = "如创科技"

  [params.homepage_meta_tags]
    meta_description = "如创科技成立于2019年8月份, 在山东青岛为云原生而生, 我们热爱云原生, 践行云原生, 推广云原生. 成立以来一直致力于服务企事业单位规划、建设、运维云原生生态. 成功建设并运维了几个中大型的容器集群, 服务上千用户, 上万个容器应用. 积累了大量实践经验."
    meta_og_title = "青岛如创科技有限公司"
    meta_og_type = "website"
    meta_og_url = "https://www.rutron.net"
    meta_og_image = "/images/logo.png"
    meta_og_description = "如创科技成立于2019年8月份, 在山东青岛为云原生而生, 我们热爱云原生, 践行云原生, 推广云原生. 成立以来一直致力于服务企事业单位规划、建设、运维云原生生态. 成功建设并运维了几个中大型的容器集群, 服务上千用户, 上万个容器应用. 积累了大量实践经验."
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
  name = "服务"
  url = "/services/"
    weight = 1

[[menu.main]]
    name = "工作"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

# [[menu.main]]
#     name = "History"
#     url = "/history/"
#     weight = 3

[[menu.main]]
    name = "联系"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
